# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-21T14:23:25Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  ports:
  - name: "80"
    nodePort: 30080
    port: 80
    targetPort: 80
  - name: "81"
    nodePort: 30081
    port: 81
    targetPort: 81
  selector:
    app: allpodd
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-21T14:23:25Z"
  labels:
    app: allpodd
  name: allpodd
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/app:latest
    imagePullPolicy: Never
    name: app
    ports:
    - containerPort: 80
    - containerPort: 81
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/bidrag-db:latest
    imagePullPolicy: Never
    name: bidrag-db
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/pseudonym-db:latest
    imagePullPolicy: Never
    name: pseudonym-db
    stdin: true
    tty: true
  - env:
    - name: TERM
      value: xterm
    image: localhost/web:latest
    imagePullPolicy: Never
    name: web
    stdin: true
    tty: true
